### ISSUE TITLE
q: what is the earliest maplibre-gl.js version this plugin supports?

### ISSUE THREAD

**Issue by igalgh** [rowanwins/maplibregl-mapbox-request-transformer#1]
For example, does it support maplibre-gl.js v1.15.2? 
Or only v2.0.0 and above?

**Comment by rowanwins** [comment]
@igal1c0de4n - good question, I'm not sure, I'm currently using it on a v2.4.0 application. I think in theory it's not required for 1.x applications because it had built-in support for mapbox urls.
