### ISSUE TITLE
How to reference this repository?

### ISSUE THREAD

**Issue by dbauszus-glx** [rowanwins/maplibregl-mapbox-request-transformer#4]
Hi Rowan,

I have modified the functions slightly to be used in my opensource project to support legacy mapbox styles with the maplibre 2+ library.

https://github.com/GEOLYTIX/xyz/pull/660

How would you like us to attribute your work?

I have for now added a link in a comment with transform method.

**Comment by rowanwins** [comment]
Hey @dbauszus-glx 
Thanks for reaching out! 

Is there anything that can be easily contributed back perhaps behind some sort of flag for supporting legacy functions? If not don't worry.

And I'm happy with you pinching the code with no attribution.

Cheers
Rowan
