### ISSUE TITLE
Mapbox maps v2

### ISSUE THREAD

**Issue by davenquinn** [rowanwins/maplibregl-mapbox-request-transformer#9]
Some of Mapbox's newer layers, such as their updated Terrain DEM model, require transitioning to their v2 billing system. It seems like, from a technical perspective, this would be a simple thing to implement by reproducing the Mapbox code to create a "sku" token at regular intervals, as is done in Mapbox GL. Is your sense that implementing this in/alongside this library would violate Mapbox's terms?

**Comment by rowanwins** [comment]
Hi @davenquinn 

Are you able to provide a mapbox style URL which shows the issue?

It doesn't look like there is much in their doco which talks about the SKU tokens other than [this](https://docs.mapbox.com/help/glossary/sku-token/) which isn't overly helpful, so it's not overly clear how they work.

I'm open to investigating a bit further though.

**Comment by davenquinn** [comment]
I did dig a bit more into this and I found the file where the tokens are generated for Mapbox GL JS:

https://github.com/mapbox/mapbox-gl-js/blob/ce76f75863b8b7ac04442a4c81cb2d6a969352b1/src/util/sku_token.js#L23

It also seems like this is referenced in the Mapbox product terms, section 2.8.3, where they discuss "qualified renderers"
https://assets-global.website-files.com/5d4296d7a839ea49599adba1/6553a6d5753a48e526edc763_Mapbox%20Product%20Terms%20(2023.11.14).pdf

So it seems like Mapbox disallows using v2 billing unless you use their renderers.

The good news is I was misinformed — seems you can use these newer layers with the v1 billing system by omitting the SKU token. Example:
```
https://api.mapbox.com/raster/v1/mapbox.mapbox-terrain-dem-v1/5/4/10.webp?access_token=<redacted>
```

**Comment by rowanwins** [comment]
Can we close this then @davenquinn ?

**Comment by davenquinn** [comment]
Yes, this seems out of scope now. Thanks for the great library!
